### ISSUE TITLE
Add requirement in readme

### ISSUE THREAD

**Issue by Yoz0** [the-lambda-church/coquille#47]
Since coquille isn't compatible with Coq 8.4pl3, it could be nice to add to the readme the version required of coqtop & vim (+python).

**Comment by trefis** [comment]
The 8.4 tag should work fine with coq 8.4pl3

**Comment by Yoz0** [comment]
Thank you, I didn't see the tag.
The current version is working with coq 8.5 or 8.6 ?

**Comment by trefis** [comment]
8.5, but "working" might be too strong a word.

**Comment by BelegCuthalion** [comment]
Well, it still would be great if you tell somewhere in the readme that it needs python
